#!/bin/sh /etc/rc.common
#
# [K] (c)2020
# http://github.com/kongfl888
#
START=99

NAME=kcpufreq

uci_get_by_type() {
    local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
    echo ${ret:=$3}
}

touchfilevaule() {
    local file=$1
    if [ -e "$file" ]; then
        local af=`cat $file | sed 's/[ \t]*//g'`
        if [ -z "$af" ];then
            echo 1
        else
            echo 0
        fi
    else
        echo 1
    fi
}

set_gov() {
    local touchgov=$(touchfilevaule "/sys/devices/system/cpu/cpufreq/policy0/scaling_governor")
    if [ $touchgov -eq 0 ];then
        echo -n $1 > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
    else
        for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
            [ -f $CPUFREQ ] || continue
            echo -n $1 > $CPUFREQ
        done
    fi
}

set_minifreq() {
    local touchmini=$(touchfilevaule "/sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq")
    if [ $touchmini -eq 0 ];then
        echo -n $1 > /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq
    else
        for minif in /sys/devices/system/cpu/cpu*/cpufreq/scaling_min_freq; do
            [ -f $minif ] || continue
            echo -n $1 > $minif
        done
    fi
}

set_maxfreq() {
    local touchmax=$(touchfilevaule "/sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq")
    if [ $touchmax -eq 0 ];then
        echo -n $1 > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
    else
        for maxf in /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq; do
            [ -f $maxf ] || continue
            echo -n $1 > $maxf
        done
    fi
}

start()
{
    config_load kcpufreq
    if [ "$enable" != "0" ]; then
        if [ ! -d "/sys/devices/system/cpu/cpufreq" -a ! -d "/sys/devices/system/cpu/cpu0/cpufreq" ];then
            echo "Kernel:cpufreq module does not exist!"
            logger "Kernel:cpufreq module does not exist!"
            return 1
        fi
        local cpumin=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq 2>/dev/null`
        local cpumax=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq 2>/dev/null`
        [ -z "$cpumin" ] && cpumin="408000"
        [ -z "$cpumax" ] && cpumax="1512000"
        local enable=$(uci_get_by_type settings enable 0)
        local advance=$(uci_get_by_type settings advance 0)
        local governor=$(uci_get_by_type settings governor schedutil)
        local minifreq=$(uci_get_by_type settings minifreq $cpumin)
        local maxfreq=$(uci_get_by_type settings maxfreq $cpumax)

        logger "cpufreq: set to $governor"
        set_gov $governor

        if [ "$advance" != "0" ]; then
            set_minifreq $minifreq
            set_maxfreq $maxfreq
        else
            set_minifreq $cpumin
            set_maxfreq $cpumax
        fi
    fi
}
